# Generated by Django 5.1.4 on 2024-12-20 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('username', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=100, unique=True)),
                ('address', models.CharField(blank=True, max_length=300, null=True)),
                ('bio', models.CharField(blank=True, max_length=400, null=True)),
                ('profile_pic', models.ImageField(blank=True, upload_to='templates')),
            ],
        ),
        migrations.CreateModel(
            name='company',
            fields=[
                ('c_username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='company', serialize=False, to='jobs.user')),
                ('company_name', models.CharField(max_length=100)),
                ('company_type', models.CharField(max_length=100)),
                ('establishment_year', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='job_seeker',
            fields=[
                ('j_username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='job_hunter', serialize=False, to='jobs.user')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('role', models.CharField(max_length=30)),
                ('gender', models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='jobs',
            fields=[
                ('job_id', models.AutoField(primary_key=True, serialize=False)),
                ('req_skill', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=100)),
                ('limit', models.IntegerField()),
                ('salary', models.DecimalField(decimal_places=3, max_digits=10)),
                ('description', models.CharField(max_length=400)),
                ('req_experience', models.IntegerField()),
                ('deadline', models.DateField()),
                ('c_username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_posted', to='jobs.company')),
            ],
        ),
        migrations.CreateModel(
            name='skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(max_length=50)),
                ('experience', models.IntegerField()),
                ('job_hunter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='jobs.job_seeker')),
            ],
        ),
        migrations.CreateModel(
            name='apply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accepted', models.BooleanField(default=False)),
                ('rejected', models.BooleanField(default=False)),
                ('cv', models.TextField()),
                ('job_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applied_jobs', to='jobs.jobs')),
                ('j_username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applied_jobs', to='jobs.job_seeker')),
            ],
        ),
    ]
